<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SlugSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Clear existing data
        DB::table('slugs')->truncate();

        // Define parent slugs (main modules)
        $parentSlugs = [
            [
                'name' => 'Dashboard',
                'slug' => 'dashboard',
                'icon' => 'fas fa-tachometer-alt',
                'parent_id' => null,
                'is_visible' => 1,
                'sort_order' => 1,
            ],
            [
                'name' => 'Human Resources',
                'slug' => 'hr',
                'icon' => 'fas fa-users',
                'parent_id' => null,
                'is_visible' => 1,
                'sort_order' => 2,
            ],
            [
                'name' => 'Attendance',
                'slug' => 'attendance',
                'icon' => 'fas fa-clock',
                'parent_id' => null,
                'is_visible' => 1,
                'sort_order' => 3,
            ],
            [
                'name' => 'Payroll',
                'slug' => 'payroll',
                'icon' => 'fas fa-money-bill-wave',
                'parent_id' => null,
                'is_visible' => 1,
                'sort_order' => 4,
            ],
            [
                'name' => 'Leave Management',
                'slug' => 'leave',
                'icon' => 'fas fa-calendar-times',
                'parent_id' => null,
                'is_visible' => 1,
                'sort_order' => 5,
            ],
            [
                'name' => 'Assets',
                'slug' => 'asset',
                'icon' => 'fas fa-boxes',
                'parent_id' => null,
                'is_visible' => 1,
                'sort_order' => 6,
            ],
            [
                'name' => 'Academic Holidays',
                'slug' => 'academic-holidays',
                'icon' => 'fas fa-calendar-alt',
                'parent_id' => null,
                'is_visible' => 1,
                'sort_order' => 7,
            ],
            [
                'name' => 'Reimbursements',
                'slug' => 'reimbursement',
                'icon' => 'fas fa-receipt',
                'parent_id' => null,
                'is_visible' => 1,
                'sort_order' => 8,
            ],
            [
                'name' => 'Announcements',
                'slug' => 'announcement',
                'icon' => 'fas fa-bullhorn',
                'parent_id' => null,
                'is_visible' => 1,
                'sort_order' => 9,
            ],
            [
                'name' => 'Handbook',
                'slug' => 'handbook',
                'icon' => 'fas fa-book',
                'parent_id' => null,
                'is_visible' => 1,
                'sort_order' => 10,
            ],
            [
                'name' => 'Field Visits',
                'slug' => 'field_visit',
                'icon' => 'fas fa-route',
                'parent_id' => null,
                'is_visible' => 1,
                'sort_order' => 11,
            ],
            [
                'name' => 'Leads',
                'slug' => 'lead',
                'icon' => 'fas fa-user-plus',
                'parent_id' => null,
                'is_visible' => 1,
                'sort_order' => 12,
            ],
            // Additional parent modules discovered in web.php
            [
                'name' => 'Super Admin',
                'slug' => 'superadmin',
                'icon' => 'fas fa-user-shield',
                'parent_id' => null,
                'is_visible' => 1,
                'sort_order' => 13,
            ],
            [
                'name' => 'Company Documents',
                'slug' => 'company-documents',
                'icon' => 'fas fa-folder-open',
                'parent_id' => null,
                'is_visible' => 1,
                'sort_order' => 18,
            ],
            [
                'name' => 'Database',
                'slug' => 'database',
                'icon' => 'fas fa-database',
                'parent_id' => null,
                'is_visible' => 1,
                'sort_order' => 18,
            ],
            [
                'name' => 'Logs',
                'slug' => 'logs',
                'icon' => 'fas fa-file-alt',
                'parent_id' => null,
                'is_visible' => 1,
                'sort_order' => 20,
            ],
            [
                'name' => 'Profile',
                'slug' => 'profile',
                'icon' => 'fas fa-user',
                'parent_id' => null,
                'is_visible' => 1,
                'sort_order' => 21,
            ],
        ];

        // Insert parent slugs and get their IDs
        $parentIds = [];
        foreach ($parentSlugs as $slug) {
            $parentIds[$slug['slug']] = DB::table('slugs')->insertGetId($slug);
        }

        // Define child slugs (sub-modules)
        $childSlugs = [
        //     // HR Management
        //     [
        //         'name' => 'Employees',
        //         'slug' => 'employee',
        //         'icon' => 'fas fa-user-tie',
        //         'parent_id' => $parentIds['hr'],
        //         'is_visible' => 1,
        //         'sort_order' => 1,
        //     ],
        //     [
        //         'name' => 'Departments',
        //         'slug' => 'department',
        //         'icon' => 'fas fa-building',
        //         'parent_id' => $parentIds['hr'],
        //         'is_visible' => 1,
        //         'sort_order' => 2,
        //     ],
        //     [
        //         'name' => 'Designations',
        //         'slug' => 'designation',
        //         'icon' => 'fas fa-id-badge',
        //         'parent_id' => $parentIds['hr'],
        //         'is_visible' => 1,
        //         'sort_order' => 3,
        //     ],
        //     [
        //         'name' => 'Teams',
        //         'slug' => 'team',
        //         'icon' => 'fas fa-users-cog',
        //         'parent_id' => $parentIds['hr'],
        //         'is_visible' => 1,
        //         'sort_order' => 4,
        //     ],
        //     [
        //         'name' => 'Employment Types',
        //         'slug' => 'employment_type',
        //         'icon' => 'fas fa-briefcase',
        //         'parent_id' => $parentIds['hr'],
        //         'is_visible' => 1,
        //         'sort_order' => 5,
        //     ],

        //     // Asset Management - route level slugs
        //     [
        //         'name' => 'Assets',
        //         'slug' => 'assets/index',
        //         'icon' => 'fas fa-boxes',
        //         'parent_id' => $parentIds['asset'],
        //         'is_visible' => 1,
        //         'sort_order' => 1,
        //     ],
        //     [
        //         'name' => 'Create Asset',
        //         'slug' => 'assets/create',
        //         'icon' => 'fas fa-handshake',
        //         'parent_id' => $parentIds['asset'],
        //         'is_visible' => 0,
        //         'sort_order' => 0,
        //     ],
        //     [
        //         'name' => 'Asset Creation',
        //         'slug' => 'assets/store',
        //         'icon' => 'fas fa-tags',
        //         'parent_id' => $parentIds['asset'],
        //         'is_visible' => 0,
        //         'sort_order' => 0,
        //     ],
        //     [
        //         'name' => 'Asset Show',
        //         'slug' => 'assets/show/{asset}',
        //         'icon' => 'fas fa-handshake',
        //         'parent_id' => $parentIds['asset'],
        //         'is_visible' => 0,
        //         'sort_order' => 0,
        //     ],
        //     [
        //         'name' => 'Edit Asset',
        //         'slug' => 'assets/{asset}/edit',
        //         'icon' => 'fas fa-edit',
        //         'parent_id' => $parentIds['asset'],
        //         'is_visible' => 0,
        //         'sort_order' => 0,
        //     ],
        //     [
        //         'name' => 'Update Asset',
        //         'slug' => 'assets/{asset}/update',
        //         'icon' => 'fas fa-save',
        //         'parent_id' => $parentIds['asset'],
        //         'is_visible' => 0,
        //         'sort_order' => 0,
        //     ],
        //     [
        //         'name' => 'Delete Asset',
        //         'slug' => 'assets/{asset}/delete',
        //         'icon' => 'fas fa-trash',
        //         'parent_id' => $parentIds['asset'],
        //         'is_visible' => 0,
        //         'sort_order' => 0,
        //     ],
        //     [
        //         'name' => 'Asset Dashboard',
        //         'slug' => 'assets/dashboard',
        //         'icon' => 'fas fa-chart-line',
        //         'parent_id' => $parentIds['asset'],
        //         'is_visible' => 1,
        //         'sort_order' => 2,
        //     ],
        //     [
        //         'name' => 'Employees with Assets',
        //         'slug' => 'assets/employees',
        //         'icon' => 'fas fa-user-tag',
        //         'parent_id' => $parentIds['asset'],
        //         'is_visible' => 1,
        //         'sort_order' => 4,
        //     ],
        //     [
        //         'name' => 'Owned Assets',
        //         'slug' => 'assets/own',
        //         'icon' => 'fas fa-tags',
        //         'parent_id' => $parentIds['asset'],
        //         'is_visible' => 1,
        //         'sort_order' => 5,
        //     ],

        //     // Asset Categories (Resource Routes)
        //         // Asset Categories (Resource Routes)
        //     [
        //         'name' => 'Asset Categories',
        //         'slug' => 'assets/categories',
        //         'icon' => 'fas fa-tags',
        //         'parent_id' => $parentIds['asset'],
        //         'is_visible' => 1,
        //         'sort_order' => 6,
        //     ],
        //     [
        //         'name' => 'Create Asset Category',
        //         'slug' => 'assets/categories/create',
        //         'icon' => 'fas fa-plus',
        //         'parent_id' => $parentIds['asset'],
        //         'is_visible' => 0,
        //         'sort_order' => 0,
        //     ],
        //     [
        //         'name' => 'Show Asset Category',
        //         'slug' => 'assets/categories/{category}',
        //         'icon' => 'fas fa-eye',
        //         'parent_id' => $parentIds['asset'],
        //         'is_visible' => 0,
        //         'sort_order' => 0,
        //     ],
        //     [
        //         'name' => 'Edit Asset Category',
        //         'slug' => 'assets/categories/{category}/edit',
        //         'icon' => 'fas fa-edit',
        //         'parent_id' => $parentIds['asset'],
        //         'is_visible' => 0,
        //         'sort_order' => 0,
        //     ],
        //     [
        //         'name' => 'Update Asset Category',
        //         'slug' => 'assets/categories/{category}/update',
        //         'icon' => 'fas fa-save',
        //         'parent_id' => $parentIds['asset'],
        //         'is_visible' => 0,
        //         'sort_order' => 0,
        //     ],
        //     [
        //         'name' => 'Delete Asset Category',
        //         'slug' => 'assets/categories/{category}/delete',
        //         'icon' => 'fas fa-trash',
        //         'parent_id' => $parentIds['asset'],
        //         'is_visible' => 0,
        //         'sort_order' => 0,
        //     ],


        //     // Asset Assignments (Nested Routes)
        //     [
        //         'name' => 'Asset Assignments',
        //         'slug' => 'assets/assignments',
        //         'icon' => 'fas fa-handshake',
        //         'parent_id' => $parentIds['asset'],
        //         'is_visible' => 1,
        //         'sort_order' => 3,
        //     ],
        //     [
        //         'name' => 'Create Asset Assignment',
        //         'slug' => 'assets/assignments/create',
        //         'icon' => 'fas fa-plus',
        //         'parent_id' => $parentIds['asset'],
        //         'is_visible' => 0,
        //         'sort_order' => 0,
        //     ],
        //     [
        //         'name' => 'Store Asset Assignment',
        //         'slug' => 'assets/assignments/store',
        //         'icon' => 'fas fa-save',
        //         'parent_id' => $parentIds['asset'],
        //         'is_visible' => 0,
        //         'sort_order' => 0,
        //     ],
        //     [
        //         'name' => 'Show Asset Assignment',
        //         'slug' => 'assets/assignments/show/{assignment}',
        //         'icon' => 'fas fa-eye',
        //         'parent_id' => $parentIds['asset'],
        //         'is_visible' => 0,
        //         'sort_order' => 0,
        //     ],
        //     [
        //         'name' => 'Edit Asset Assignment',
        //         'slug' => 'assets/assignments/{assignment}/edit',
        //         'icon' => 'fas fa-edit',
        //         'parent_id' => $parentIds['asset'],
        //         'is_visible' => 0,
        //         'sort_order' => 0,
        //     ],
        //     [
        //         'name' => 'Update Asset Assignment',
        //         'slug' => 'assets/assignments/{assignment}/update',
        //         'icon' => 'fas fa-save',
        //         'parent_id' => $parentIds['asset'],
        //         'is_visible' => 0,
        //         'sort_order' => 0,
        //     ],
        //     [
        //         'name' => 'Delete Asset Assignment',
        //         'slug' => 'assets/assignments/{assignment}/delete',
        //         'icon' => 'fas fa-trash',
        //         'parent_id' => $parentIds['asset'],
        //         'is_visible' => 0,
        //         'sort_order' => 0,
        //     ],
        //     [
        //         'name' => 'Return Asset',
        //         'slug' => 'assets/assignments/{assignment}/return',
        //         'icon' => 'fas fa-undo',
        //         'parent_id' => $parentIds['asset'],
        //         'is_visible' => 0,
        //         'sort_order' => 0,
        //     ],
        //     [
        //         'name' => 'Recent Assignments',
        //         'slug' => 'assets/assignments/recent',
        //         'icon' => 'fas fa-clock',
        //         'parent_id' => $parentIds['asset'],
        //         'is_visible' => 0,
        //         'sort_order' => 0,
        //     ],

        //     // Academic Holidays
        //     [
        //         'name' => 'Academic Holidays',
        //         'slug' => 'academic-holidays/index',
        //         'icon' => 'fas fa-calendar-alt',
        //         'parent_id' => $parentIds['academic-holidays'],
        //         'is_visible' => 1,
        //         'sort_order' => 1,
        //     ],
        //     [
        //         'name' => 'Create Academic Holiday',
        //         'slug' => 'academic-holidays/create',
        //         'icon' => 'fas fa-plus',
        //         'parent_id' => $parentIds['academic-holidays'],
        //         'is_visible' => 0,
        //         'sort_order' => 0,
        //     ],
        //     [
        //         'name' => 'Store Academic Holiday',
        //         'slug' => 'academic-holidays/store',
        //         'icon' => 'fas fa-save',
        //         'parent_id' => $parentIds['academic-holidays'],
        //         'is_visible' => 0,
        //         'sort_order' => 0,
        //     ],
        //     [
        //         'name' => 'Edit Academic Holiday',
        //         'slug' => 'academic-holidays/{holiday}/edit',
        //         'icon' => 'fas fa-edit',
        //         'parent_id' => $parentIds['academic-holidays'],
        //         'is_visible' => 0,
        //         'sort_order' => 0,
        //     ],
        //     [
        //         'name' => 'Update Academic Holiday',
        //         'slug' => 'academic-holidays/{holiday}/update',
        //         'icon' => 'fas fa-save',
        //         'parent_id' => $parentIds['academic-holidays'],
        //         'is_visible' => 0,
        //         'sort_order' => 0,
        //     ],
        //     [
        //         'name' => 'Delete Academic Holiday',
        //         'slug' => 'academic-holidays/{holiday}/delete',
        //         'icon' => 'fas fa-trash',
        //         'parent_id' => $parentIds['academic-holidays'],
        //         'is_visible' => 0,
        //         'sort_order' => 0,
        //     ],
        //     [
        //         'name' => 'Import Academic Holidays',
        //         'slug' => 'academic-holidays/import',
        //         'icon' => 'fas fa-upload',
        //         'parent_id' => $parentIds['academic-holidays'],
        //         'is_visible' => 0,
        //         'sort_order' => 0,
        //     ],
        //     [
        //         'name' => 'Download Academic Holiday Template',
        //         'slug' => 'academic-holidays/template',
        //         'icon' => 'fas fa-download',
        //         'parent_id' => $parentIds['academic-holidays'],
        //         'is_visible' => 0,
        //         'sort_order' => 0,
        //     ],

        //     // Super Admin / Packages / Settings
        //     [
        //         'name' => 'Companies (SuperAdmin)',
        //         'slug' => 'superadmin/companies',
        //         'icon' => 'fas fa-building',
        //         'parent_id' => $parentIds['superadmin'],
        //         'is_visible' => 1,
        //         'sort_order' => 1,
        //     ],
        //     [
        //         'name' => 'View Company',
        //         'slug' => 'superadmin/companies/{company}',
        //         'icon' => 'fas fa-eye',
        //         'parent_id' => $parentIds['superadmin'],
        //         'is_visible' => 0,
        //         'sort_order' => 0,
        //     ],
        //     [
        //         'name' => 'Company\'s Documents',
        //         'slug' => 'superadmin/companies/{company}/documents',
        //         'icon' => 'fas fa-file',
        //         'parent_id' => $parentIds['superadmin'],
        //         'is_visible' => 0,
        //         'sort_order' => 0,
        //     ],
        //     [
        //         'name' => 'Create Company',
        //         'slug' => 'superadmin/companies/create',
        //         'icon' => 'fas fa-plus',
        //         'parent_id' => $parentIds['superadmin'],
        //         'is_visible' => 0,
        //         'sort_order' => 0,
        //     ],
        //     [
        //         'name' => 'Store Company',
        //         'slug' => 'superadmin/companies/store',
        //         'icon' => 'fas fa-save',
        //         'parent_id' => $parentIds['superadmin'],
        //         'is_visible' => 0,
        //         'sort_order' => 0,
        //     ],
        //     [
        //         'name' => 'Edit Company',
        //         'slug' => 'superadmin/companies/{company}/edit',
        //         'icon' => 'fas fa-edit',
        //         'parent_id' => $parentIds['superadmin'],
        //         'is_visible' => 0,
        //         'sort_order' => 0,
        //     ],
        //     [
        //         'name' => 'Update Company',
        //         'slug' => 'superadmin/companies/{company}/update',
        //         'icon' => 'fas fa-save',
        //         'parent_id' => $parentIds['superadmin'],
        //         'is_visible' => 0,
        //         'sort_order' => 0,
        //     ],

        //     [
        //         'name' => 'SuperAdmin - Users',
        //         'slug' => 'superadmin/users',
        //         'icon' => 'fas fa-users',
        //         'parent_id' => $parentIds['superadmin'],
        //         'is_visible' => 1,
        //         'sort_order' => 2,
        //     ],
        //     [
        //         'name' => 'SuperAdmin - Edit User',
        //         'slug' => 'superadmin/user/{user}/edit',
        //         'icon' => 'fas fa-edit',
        //         'parent_id' => $parentIds['superadmin'],
        //         'is_visible' => 0,
        //         'sort_order' => 0,
        //     ],
        //     [
        //         'name' => 'SuperAdmin - Update User',
        //         'slug' => 'superadmin/user/{user}/update',
        //         'icon' => 'fas fa-save',
        //         'parent_id' => $parentIds['superadmin'],
        //         'is_visible' => 0,
        //         'sort_order' => 0,
        //     ],
        //     [
        //         'name' => 'SuperAdmin - Delete User',
        //         'slug' => 'superadmin/user/{user}/delete',
        //         'icon' => 'fas fa-trash',
        //         'parent_id' => $parentIds['superadmin'],
        //         'is_visible' => 0,
        //         'sort_order' => 0,
        //     ],
        //     [
        //         'name' => 'Assign Company Admins',
        //         'slug' => 'assign-company-admin',
        //         'icon' => 'fas fa-user-cog',
        //         'parent_id' => $parentIds['superadmin'],
        //         'is_visible' => 1,
        //         'sort_order' => 2,
        //     ],
        //     [
        //         'name' => 'Assigned Company Admins',
        //         'slug' => 'assigned-company-admins',
        //         'icon' => 'fas fa-users',
        //         'parent_id' => $parentIds['superadmin'],
        //         'is_visible' => 1,
        //         'sort_order' => 3,
        //     ],
        //     [
        //         'name' => 'Create Company Admin Assignment',
        //         'slug' => 'assign-company-admin/create',
        //         'icon' => 'fas fa-plus',
        //         'parent_id' => $parentIds['superadmin'],
        //         'is_visible' => 0,
        //         'sort_order' => 0,
        //     ],
        //     [
        //         'name' => 'Store Company Admin Assignment',
        //         'slug' => 'assign-company-admin/store',
        //         'icon' => 'fas fa-save',
        //         'parent_id' => $parentIds['superadmin'],
        //         'is_visible' => 0,
        //         'sort_order' => 0,
        //     ],
        //     [
        //         'name' => 'Edit Company Admin Assignment',
        //         'slug' => 'assign-company-admin/{assign_company_admin}/edit',
        //         'icon' => 'fas fa-edit',
        //         'parent_id' => $parentIds['superadmin'],
        //         'is_visible' => 0,
        //         'sort_order' => 0,
        //     ],
        //     [
        //         'name' => 'Update Company Admin Assignment',
        //         'slug' => 'assign-company-admin/{assign_company_admin}/update',
        //         'icon' => 'fas fa-save',
        //         'parent_id' => $parentIds['superadmin'],
        //         'is_visible' => 0,
        //         'sort_order' => 0,
        //     ],
        //     [
        //         'name' => 'Delete Company Admin Assignment',
        //         'slug' => 'assign-company-admin/{assign_company_admin}/destroy',
        //         'icon' => 'fas fa-trash',
        //         'parent_id' => $parentIds['superadmin'],
        //         'is_visible' => 0,
        //         'sort_order' => 0,
        //     ],
        //     [
        //         'name' => 'Slug Settings',
        //         'slug' => 'setting/slugs',
        //         'icon' => 'fas fa-sliders-h',
        //         'parent_id' => $parentIds['superadmin'],
        //         'is_visible' => 1,
        //         'sort_order' => 4,
        //     ],
        //     [
        //         'name' => 'Add Slug',
        //         'slug' => 'setting/slug/add',
        //         'icon' => 'fas fa-plus',
        //         'parent_id' => $parentIds['superadmin'],
        //         'is_visible' => 0,
        //         'sort_order' => 0,
        //     ],
        //     [
        //         'name' => 'Edit Slug (GET)',
        //         'slug' => 'setting/slug/edit/{id}',
        //         'icon' => 'fas fa-edit',
        //         'parent_id' => $parentIds['superadmin'],
        //         'is_visible' => 0,
        //         'sort_order' => 0,
        //     ],
        //     [
        //         'name' => 'Edit Slug (POST)',
        //         'slug' => 'setting/slug/edit/{id}',
        //         'icon' => 'fas fa-save',
        //         'parent_id' => $parentIds['superadmin'],
        //         'is_visible' => 0,
        //         'sort_order' => 0,
        //     ],
        //     [
        //         'name' => 'Delete Slug',
        //         'slug' => 'setting/slug/destroy/{id}',
        //         'icon' => 'fas fa-trash',
        //         'parent_id' => $parentIds['superadmin'],
        //         'is_visible' => 0,
        //         'sort_order' => 0,
        //     ],
        //     [
        //         'name' => 'Deactivate Company',
        //         'slug' => 'superadmin/companies/{id}/deactivate',
        //         'icon' => 'fas fa-ban',
        //         'parent_id' => $parentIds['superadmin'],
        //         'is_visible' => 0,
        //         'sort_order' => 0,
        //     ],
        //     [
        //         'name' => 'Activate Company',
        //         'slug' => 'superadmin/companies/{id}/activate',
        //         'icon' => 'fas fa-check-circle',
        //         'parent_id' => $parentIds['superadmin'],
        //         'is_visible' => 0,
        //         'sort_order' => 0,
        //     ],
        //     [
        //         'name' => 'Deactivate Employee',
        //         'slug' => 'superadmin/companies/{companyId}/employees/{employeeId}/deactivate',
        //         'icon' => 'fas fa-user-slash',
        //         'parent_id' => $parentIds['superadmin'],
        //         'is_visible' => 0,
        //         'sort_order' => 0,
        //     ],
        //     [
        //         'name' => 'Activate Employee',
        //         'slug' => 'superadmin/companies/{companyId}/employees/{employeeId}/activate',
        //         'icon' => 'fas fa-user-check',
        //         'parent_id' => $parentIds['superadmin'],
        //         'is_visible' => 0,
        //         'sort_order' => 0,
        //     ],
        //     [
        //         'name' => 'SuperAdmin Roles',
        //         'slug' => 'superadmin/roles',
        //         'icon' => 'fas fa-user-tag',
        //         'parent_id' => $parentIds['superadmin'],
        //         'is_visible' => 1,
        //         'sort_order' => 5,
        //     ],
        //     [
        //         'name' => 'Create SuperAdmin Role',
        //         'slug' => 'superadmin/roles/create',
        //         'icon' => 'fas fa-plus',
        //         'parent_id' => $parentIds['superadmin'],
        //         'is_visible' => 0,
        //         'sort_order' => 0,
        //     ],
        //     [
        //         'name' => 'Store SuperAdmin Role',
        //         'slug' => 'superadmin/roles/store',
        //         'icon' => 'fas fa-save',
        //         'parent_id' => $parentIds['superadmin'],
        //         'is_visible' => 0,
        //         'sort_order' => 0,
        //     ],
        //     [
        //         'name' => 'Show SuperAdmin Role',
        //         'slug' => 'superadmin/roles/{role}',
        //         'icon' => 'fas fa-eye',
        //         'parent_id' => $parentIds['superadmin'],
        //         'is_visible' => 0,
        //         'sort_order' => 0,
        //     ],
        //     [
        //         'name' => 'Edit SuperAdmin Role',
        //         'slug' => 'superadmin/roles/{role}/edit',
        //         'icon' => 'fas fa-edit',
        //         'parent_id' => $parentIds['superadmin'],
        //         'is_visible' => 0,
        //         'sort_order' => 0,
        //     ],
        //     [
        //         'name' => 'Update SuperAdmin Role',
        //         'slug' => 'superadmin/roles/{role}/update',
        //         'icon' => 'fas fa-save',
        //         'parent_id' => $parentIds['superadmin'],
        //         'is_visible' => 0,
        //         'sort_order' => 0,
        //     ],
        //     [
        //         'name' => 'Delete SuperAdmin Role',
        //         'slug' => 'superadmin/roles/{role}/destroy',
        //         'icon' => 'fas fa-trash',
        //         'parent_id' => $parentIds['superadmin'],
        //         'is_visible' => 0,
        //         'sort_order' => 0,
        //     ],

        //     // Company Documents
        //     [
        //         'name' => 'Company Documents',
        //         'slug' => 'companies/{company}/documents',
        //         'icon' => 'fas fa-folder-open',
        //         'parent_id' => $parentIds['company-documents'],
        //         'is_visible' => 1,
        //         'sort_order' => 1,
        //     ],
        //     [
        //         'name' => 'Upload Company Document',
        //         'slug' => 'companies/{company}/documents/upload',
        //         'icon' => 'fas fa-upload',
        //         'parent_id' => $parentIds['company-documents'],
        //         'is_visible' => 0,
        //         'sort_order' => 0,
        //     ],
        //     [
        //         'name' => 'Verify Company Document',
        //         'slug' => 'companies/{company}/documents/{document}/verify',
        //         'icon' => 'fas fa-check-circle',
        //         'parent_id' => $parentIds['company-documents'],
        //         'is_visible' => 0,
        //         'sort_order' => 0,
        //     ],
        //     [
        //         'name' => 'Reject Company Document',
        //         'slug' => 'companies/{company}/documents/{document}/reject',
        //         'icon' => 'fas fa-times-circle',
        //         'parent_id' => $parentIds['company-documents'],
        //         'is_visible' => 0,
        //         'sort_order' => 0,
        //     ],

        //     // Database & Logs
        //     [
        //         'name' => 'Database',
        //         'slug' => 'database/index',
        //         'icon' => 'fas fa-database',
        //         'parent_id' => $parentIds['database'],
        //         'is_visible' => 1,
        //         'sort_order' => 1,
        //     ],
        //     [
        //         'name' => 'Database Table (GET)',
        //         'slug' => 'database/table/{table}',
        //         'icon' => 'fas fa-table',
        //         'parent_id' => $parentIds['database'],
        //         'is_visible' => 0,
        //         'sort_order' => 0,
        //     ],
        //     [
        //         'name' => 'Database Table (POST)',
        //         'slug' => 'database/table/{table}',
        //         'icon' => 'fas fa-search',
        //         'parent_id' => $parentIds['database'],
        //         'is_visible' => 0,
        //         'sort_order' => 0,
        //     ],
        //     [
        //         'name' => 'Export Table',
        //         'slug' => 'database/table/{table}/export',
        //         'icon' => 'fas fa-file-export',
        //         'parent_id' => $parentIds['database'],
        //         'is_visible' => 0,
        //         'sort_order' => 0,
        //     ],
        //     [
        //         'name' => 'Export Database',
        //         'slug' => 'database/export',
        //         'icon' => 'fas fa-file-export',
        //         'parent_id' => $parentIds['database'],
        //         'is_visible' => 0,
        //         'sort_order' => 0,
        //     ],
        //     [
        //         'name' => 'Database Query',
        //         'slug' => 'database/query',
        //         'icon' => 'fas fa-search',
        //         'parent_id' => $parentIds['database'],
        //         'is_visible' => 0,
        //         'sort_order' => 0,
        //     ],

        //     [
        //         'name' => 'Logs',
        //         'slug' => 'logs/index',
        //         'icon' => 'fas fa-file-alt',
        //         'parent_id' => $parentIds['logs'],
        //         'is_visible' => 1,
        //         'sort_order' => 1,
        //     ],
        //     [
        //         'name' => 'View Log',
        //         'slug' => 'logs/{filename}',
        //         'icon' => 'fas fa-eye',
        //         'parent_id' => $parentIds['logs'],
        //         'is_visible' => 0,
        //         'sort_order' => 0,
        //     ],
        //     [
        //         'name' => 'Download Log',
        //         'slug' => 'logs/{filename}/download',
        //         'icon' => 'fas fa-download',
        //         'parent_id' => $parentIds['logs'],
        //         'is_visible' => 0,
        //         'sort_order' => 0,
        //     ],

        //     // Admin Payroll (grouped under payroll parent)
        //     [
        //         'name' => 'Admin Payroll Index',
        //         'slug' => 'admin/payroll',
        //         'icon' => 'fas fa-money-bill-wave',
        //         'parent_id' => $parentIds['payroll'],
        //         'is_visible' => 1,
        //         'sort_order' => 1,
        //     ],
        //     [
        //         'name' => 'Admin Payroll Create',
        //         'slug' => 'admin/payroll/create',
        //         'icon' => 'fas fa-plus',
        //         'parent_id' => $parentIds['payroll'],
        //         'is_visible' => 0,
        //         'sort_order' => 0,
        //     ],
        //     [
        //         'name' => 'Admin Payroll Show',
        //         'slug' => 'admin/payroll/{payroll}',
        //         'icon' => 'fas fa-eye',
        //         'parent_id' => $parentIds['payroll'],
        //         'is_visible' => 0,
        //         'sort_order' => 0,
        //     ],
        //     [
        //         'name' => 'Process Payroll',
        //         'slug' => 'admin/payroll/{payroll}/process',
        //         'icon' => 'fas fa-play',
        //         'parent_id' => $parentIds['payroll'],
        //         'is_visible' => 0,
        //         'sort_order' => 0,
        //     ],
        //     [
        //         'name' => 'Mark Payroll Paid',
        //         'slug' => 'admin/payroll/{payroll}/mark-as-paid',
        //         'icon' => 'fas fa-check',
        //         'parent_id' => $parentIds['payroll'],
        //         'is_visible' => 0,
        //         'sort_order' => 0,
        //     ],

        //     // Beneficiary Badges
        //     [
        //         'name' => 'Beneficiary Badges',
        //         'slug' => 'admin/payroll/beneficiary-badges/index',
        //         'icon' => 'fas fa-money-bill-wave',
        //         'parent_id' => $parentIds['payroll'],
        //         'is_visible' => 1,
        //         'sort_order' => 4,
        //     ],
        //     [
        //         'name' => 'Create Beneficiary Badge',
        //         'slug' => 'admin/payroll/beneficiary-badges/create',
        //         'icon' => 'fas fa-plus',
        //         'parent_id' => $parentIds['payroll'],
        //         'is_visible' => 0,
        //         'sort_order' => 0,
        //     ],
        //     [
        //         'name' => 'Show Beneficiary Badge',
        //         'slug' => 'admin/payroll/beneficiary-badges/{beneficiary_badge}',
        //         'icon' => 'fas fa-eye',
        //         'parent_id' => $parentIds['payroll'],
        //         'is_visible' => 0,
        //         'sort_order' => 0,
        //     ],
        //     [
        //         'name' => 'Edit Beneficiary Badge',
        //         'slug' => 'admin/payroll/beneficiary-badges/{beneficiary_badge}/edit',
        //         'icon' => 'fas fa-edit',
        //         'parent_id' => $parentIds['payroll'],
        //         'is_visible' => 0,
        //         'sort_order' => 0,
        //     ],
        //     [
        //         'name' => 'Apply Beneficiary Badge to All',
        //         'slug' => 'admin/payroll/beneficiary-badges/{beneficiary_badge}/apply-to-all',
        //         'icon' => 'fas fa-users',
        //         'parent_id' => $parentIds['payroll'],
        //         'is_visible' => 0,
        //         'sort_order' => 0,
        //     ],
        //     [
        //         'name' => 'API Apply Beneficiary Badge to All',
        //         'slug' => 'admin/payroll/beneficiary-badges/{beneficiary_badge}/api/apply-to-all',
        //         'icon' => 'fas fa-users',
        //         'parent_id' => $parentIds['payroll'],
        //         'is_visible' => 0,
        //         'sort_order' => 0,
        //     ],

        //     // Employee Payroll (employee/payroll)
        //     [
        //         'name' => 'My Payslips',
        //         'slug' => 'employee/payroll',
        //         'icon' => 'fas fa-file-invoice',
        //         'parent_id' => $parentIds['payroll'],
        //         'is_visible' => 1,
        //         'sort_order' => 2,
        //     ],
        //     [
        //         'name' => 'View Payslip',
        //         'slug' => 'employee/payroll/{payroll}',
        //         'icon' => 'fas fa-eye',
        //         'parent_id' => $parentIds['payroll'],
        //         'is_visible' => 0,
        //         'sort_order' => 0,
        //     ],
        //     [
        //         'name' => 'Download Payslip',
        //         'slug' => 'employee/payroll/{payroll}/download',
        //         'icon' => 'fas fa-download',
        //         'parent_id' => $parentIds['payroll'],
        //         'is_visible' => 0,
        //         'sort_order' => 0,
        //     ],

        //     // Attendance (admin + employee)
        //     [
        //         'name' => 'Admin Attendance',
        //         'slug' => 'attendance/index',
        //         'icon' => 'fas fa-clock',
        //         'parent_id' => $parentIds['attendance'],
        //         'is_visible' => 1,
        //         'sort_order' => 1,
        //     ],
        //     [
        //         'name' => 'Attendance Summary',
        //         'slug' => 'attendance/summary',
        //         'icon' => 'fas fa-chart-line',
        //         'parent_id' => $parentIds['attendance'],
        //         'is_visible' => 0,
        //         'sort_order' => 0,
        //     ],
        //     [
        //         'name' => 'Attendance Import',
        //         'slug' => 'attendance/import',
        //         'icon' => 'fas fa-file-upload',
        //         'parent_id' => $parentIds['attendance'],
        //         'is_visible' => 0,
        //         'sort_order' => 0,
        //     ],
        //     [
        //         'name' => 'Attendance Export',
        //         'slug' => 'attendance/export',
        //         'icon' => 'fas fa-file-export',
        //         'parent_id' => $parentIds['attendance'],
        //         'is_visible' => 0,
        //         'sort_order' => 0,
        //     ],
        //     [
        //         'name' => 'My Attendance Dashboard',
        //         'slug' => 'attendance/dashboard',
        //         'icon' => 'fas fa-tachometer-alt',
        //         'parent_id' => $parentIds['attendance'],
        //         'is_visible' => 1,
        //         'sort_order' => 2,
        //     ],
        //     [
        //         'name' => 'Check In/Out',
        //         'slug' => 'attendance/check-in-out',
        //         'icon' => 'fas fa-sign-in-alt',
        //         'parent_id' => $parentIds['attendance'],
        //         'is_visible' => 1,
        //         'sort_order' => 3,
        //     ],
        //     [
        //         'name' => 'Attendance Check In',
        //         'slug' => 'attendance/check-in',
        //         'icon' => 'fas fa-sign-in',
        //         'parent_id' => $parentIds['attendance'],
        //         'is_visible' => 0,
        //         'sort_order' => 0,
        //     ],
        //     [
        //         'name' => 'Attendance Check Out',
        //         'slug' => 'attendance/check-out',
        //         'icon' => 'fas fa-sign-out',
        //         'parent_id' => $parentIds['attendance'],
        //         'is_visible' => 0,
        //         'sort_order' => 0,
        //     ],
        //     [
        //         'name' => 'Attendance Settings',
        //         'slug' => 'attendance/settings',
        //         'icon' => 'fas fa-cogs',
        //         'parent_id' => $parentIds['attendance'],
        //         'is_visible' => 1,
        //         'sort_order' => 4,
        //     ],
        //     [
        //         'name' => 'Attendance Settings View',
        //         'slug' => 'attendance/settings/view',
        //         'icon' => 'fas fa-eye',
        //         'parent_id' => $parentIds['attendance'],
        //         'is_visible' => 0,
        //         'sort_order' => 0,
        //     ],
        //     [
        //         'name' => 'Update Attendance Settings (POST)',
        //         'slug' => 'attendance/settings',
        //         'icon' => 'fas fa-save',
        //         'parent_id' => $parentIds['attendance'],
        //         'is_visible' => 0,
        //         'sort_order' => 0,
        //     ],
        //     [
        //         'name' => 'Update Attendance Settings (PUT)',
        //         'slug' => 'attendance/settings',
        //         'icon' => 'fas fa-save',
        //         'parent_id' => $parentIds['attendance'],
        //         'is_visible' => 0,
        //         'sort_order' => 0,
        //     ],

        //     // Leaves (additional entries)
        //     [
        //         'name' => 'Leave Requests (admin)',
        //         'slug' => 'leave-requests',
        //         'icon' => 'fas fa-paper-plane',
        //         'parent_id' => $parentIds['leave'],
        //         'is_visible' => 1,
        //         'sort_order' => 1,
        //     ],
        //     [
        //         'name' => 'Leave Types',
        //         'slug' => 'leave-types',
        //         'icon' => 'fas fa-list',
        //         'parent_id' => $parentIds['leave'],
        //         'is_visible' => 1,
        //         'sort_order' => 2,
        //     ],

        //     // Shifts
        //     [
        //         'name' => 'Shifts',
        //         'slug' => 'shifts',
        //         'icon' => 'fas fa-clock',
        //         'parent_id' => $parentIds['hr'],
        //         'is_visible' => 1,
        //         'sort_order' => 10,
        //     ],
        //     [
        //         'name' => 'Assign Shift',
        //         'slug' => 'shifts/{shift}/assign',
        //         'icon' => 'fas fa-user-clock',
        //         'parent_id' => $parentIds['hr'],
        //         'is_visible' => 0,
        //         'sort_order' => 0,
        //     ],

        //     // Handbooks
        //     [
        //         'name' => 'Handbooks',
        //         'slug' => 'handbooks',
        //         'icon' => 'fas fa-book',
        //         'parent_id' => $parentIds['handbook'],
        //         'is_visible' => 1,
        //         'sort_order' => 1,
        //     ],

        //     // Field Visits
        //     [
        //         'name' => 'Field Visits',
        //         'slug' => 'field-visits',
        //         'icon' => 'fas fa-route',
        //         'parent_id' => $parentIds['field_visit'],
        //         'is_visible' => 1,
        //         'sort_order' => 1,
        //     ],

        //     // Designations / Departments / Employment Types
        //     [
        //         'name' => 'Designations',
        //         'slug' => 'designations',
        //         'icon' => 'fas fa-id-badge',
        //         'parent_id' => $parentIds['hr'],
        //         'is_visible' => 1,
        //         'sort_order' => 5,
        //     ],
        //     [
        //         'name' => 'Departments',
        //         'slug' => 'departments',
        //         'icon' => 'fas fa-building',
        //         'parent_id' => $parentIds['hr'],
        //         'is_visible' => 1,
        //         'sort_order' => 6,
        //     ],
        //     [
        //         'name' => 'Employment Types',
        //         'slug' => 'employment-types',
        //         'icon' => 'fas fa-briefcase',
        //         'parent_id' => $parentIds['hr'],
        //         'is_visible' => 1,
        //         'sort_order' => 7,
        //     ],

        //     // Reimbursements
        //     [
        //         'name' => 'Reimbursements',
        //         'slug' => 'reimbursements',
        //         'icon' => 'fas fa-receipt',
        //         'parent_id' => $parentIds['reimbursement'],
        //         'is_visible' => 1,
        //         'sort_order' => 1,
        //     ],
        //     [
        //         'name' => 'Approve Reimbursement',
        //         'slug' => 'reimbursements/{reimbursement}/approve',
        //         'icon' => 'fas fa-check',
        //         'parent_id' => $parentIds['reimbursement'],
        //         'is_visible' => 0,
        //         'sort_order' => 0,
        //     ],

        //     // Employees Management (company-admin)
        //     [
        //         'name' => 'Employees Management',
        //         'slug' => 'employees-management',
        //         'icon' => 'fas fa-users',
        //         'parent_id' => $parentIds['hr'],
        //         'is_visible' => 1,
        //         'sort_order' => 20,
        //     ],

        //     // Company Admin Payslips
        //     [
        //         'name' => 'Company Admin Payslips',
        //         'slug' => 'company-admin/payslips',
        //         'icon' => 'fas fa-file-invoice',
        //         'parent_id' => $parentIds['payroll'],
        //         'is_visible' => 1,
        //         'sort_order' => 30,
        //     ],

        //     // Dashboard routes
        //     [
        //         'name' => 'Home Dashboard',
        //         'slug' => 'home',
        //         'icon' => 'fas fa-home',
        //         'parent_id' => $parentIds['dashboard'],
        //         'is_visible' => 1,
        //         'sort_order' => 1,
        //     ],
        //     [
        //         'name' => 'Blank Page',
        //         'slug' => 'blank',
        //         'icon' => 'fas fa-file',
        //         'parent_id' => $parentIds['dashboard'],
        //         'is_visible' => 0,
        //         'sort_order' => 0,
        //     ],

        //     // Profile routes
        //     [
        //         'name' => 'Edit Profile',
        //         'slug' => 'profile/edit',
        //         'icon' => 'fas fa-edit',
        //         'parent_id' => $parentIds['profile'],
        //         'is_visible' => 1,
        //         'sort_order' => 1,
        //     ],
        //     [
        //         'name' => 'Update Profile',
        //         'slug' => 'profile/update',
        //         'icon' => 'fas fa-save',
        //         'parent_id' => $parentIds['profile'],
        //         'is_visible' => 0,
        //         'sort_order' => 0,
        //     ],
        //     [
        //         'name' => 'Change Password',
        //         'slug' => 'profile/change-password',
        //         'icon' => 'fas fa-key',
        //         'parent_id' => $parentIds['profile'],
        //         'is_visible' => 1,
        //         'sort_order' => 2,
        //     ],
        //     [
        //         'name' => 'Update Password',
        //         'slug' => 'profile/password',
        //         'icon' => 'fas fa-lock',
        //         'parent_id' => $parentIds['profile'],
        //         'is_visible' => 0,
        //         'sort_order' => 0,
        //     ],

        //     // Generic / debugging routes
        //     [
        //         'name' => 'Run Attendance Command',
        //         'slug' => 'run-attendance/{date?}',
        //         'icon' => 'fas fa-play-circle',
        //         'parent_id' => $parentIds['attendance'],
        //         'is_visible' => 0,
        //         'sort_order' => 0,
        //     ],

        ];

        // Insert child slugs
        foreach ($childSlugs as $slug) {
            DB::table('slugs')->insert($slug);
        }

        $this->command->info('Slug seeder completed successfully!');
        $this->command->info('Created ' . count($parentSlugs) . ' parent slugs and ' . count($childSlugs) . ' child slugs.');
    }
}
